### ISSUE TITLE
AttributeError: 'list' object has no attribute 'ndim' [Solved]

### ISSUE THREAD

**Issue by baxter100** [lbechberger/ConceptualSpaces#1] opened 2018-04-16 16:41 UTC
I was running the code and getting the error 'AttributeError: 'list' object has no attribute 'ndim'' when running the fruit_space.py example. This seems to be happening because one of the variables (z) was not an np.array object.

I seem to have resolved this by editing concept_inspector.py --- importing `numpy as np` and then adding `z=np.array(z)` in the `_draw_concept` function before `this._ax_3d.plot_surface` is called.

**Comment by lbechberger** [comment] 2018-04-18 13:09
Thanks for pointing this out! 
I can't reproduce this on my machine, but I've changed the code to use numpy arrays for the 3d visualization. Can you check whether this solves your problem?

**Comment by baxter100** [comment] 2018-04-19 11:03
I'm now getting this error:
"Traceback (most recent call last):
  File "fruit_space.py", line 101, in <module>
    ci.init()
  File "../visualization/concept_inspector.py", line 202, in init
    first_dim_radios_ax = this._fig.add_axes([0.025, 0.95 - 0.03 * space._n_dim, 0.12, 0.03 * space._n_dim], axisbg='w') 
  File "/home/atp/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1136, in add_axes
    a = projection_class(self, rect, **kwargs)
  File "/home/atp/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 539, in __init__
    self.update(kwargs)
  File "/home/atp/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 888, in update
    for k, v in props.items()]
  File "/home/atp/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 881, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property axisbg"


The matplotlib version I'm using is  2.2.2 and Python is 2.7.14

**Comment by lbechberger** [comment] 2018-06-07 11:11
Sorry for the long silence, I've been very busy with other things. I'll try to set up a virtual environment sometime in the next weeks in order to make these things better reproducible. Maybe that will even solve the problem (if it's a dependency problem). I'll keep you posted.

**Comment by lbechberger** [comment] 2018-06-14 08:22
I now created a conda environment called ConceptualSpaces (see environment.yml in the project's root directory). Can you try to use that environment (see https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file for instructions) and let me know whether you still experience weird errors?

**Comment by lbechberger** [comment] 2020-10-30 07:14
Since there has been silence on this topic, and since I'm going to attend to the pull request #3 by Marius Pol (which will likely involve setting up a new virtual environment for python 3), I'm now closing this issue.

**Closed as completed by lbechberger** 2020-10-30 07:14 UTC
